package com.example.domain;

import java.util.Date;

public class Admins {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.password
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.deleted
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.id
     *
     * @return the value of admins.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.id
     *
     * @param id the value for admins.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.name
     *
     * @return the value of admins.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.name
     *
     * @param name the value for admins.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.email
     *
     * @return the value of admins.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.email
     *
     * @param email the value for admins.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.zipcode
     *
     * @return the value of admins.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.zipcode
     *
     * @param zipcode the value for admins.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.address
     *
     * @return the value of admins.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.address
     *
     * @param address the value for admins.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.tel
     *
     * @return the value of admins.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.tel
     *
     * @param tel the value for admins.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.password
     *
     * @return the value of admins.password
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.password
     *
     * @param password the value for admins.password
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.created_at
     *
     * @return the value of admins.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.created_at
     *
     * @param createdAt the value for admins.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.updated_at
     *
     * @return the value of admins.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.updated_at
     *
     * @param updatedAt the value for admins.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.deleted
     *
     * @return the value of admins.deleted
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.deleted
     *
     * @param deleted the value for admins.deleted
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}