package com.example.domain;

import java.util.Date;

public class Buildings {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.building_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String buildingName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.building_zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String buildingZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.building_address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String buildingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.id
     *
     * @return the value of buildings.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.id
     *
     * @param id the value for buildings.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.building_name
     *
     * @return the value of buildings.building_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getBuildingName() {
        return buildingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.building_name
     *
     * @param buildingName the value for buildings.building_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName == null ? null : buildingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.building_zipcode
     *
     * @return the value of buildings.building_zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getBuildingZipcode() {
        return buildingZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.building_zipcode
     *
     * @param buildingZipcode the value for buildings.building_zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBuildingZipcode(String buildingZipcode) {
        this.buildingZipcode = buildingZipcode == null ? null : buildingZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.building_address
     *
     * @return the value of buildings.building_address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getBuildingAddress() {
        return buildingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.building_address
     *
     * @param buildingAddress the value for buildings.building_address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBuildingAddress(String buildingAddress) {
        this.buildingAddress = buildingAddress == null ? null : buildingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.comment
     *
     * @return the value of buildings.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.comment
     *
     * @param comment the value for buildings.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.creator_id
     *
     * @return the value of buildings.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.creator_id
     *
     * @param creatorId the value for buildings.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.created_at
     *
     * @return the value of buildings.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.created_at
     *
     * @param createdAt the value for buildings.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.updater_id
     *
     * @return the value of buildings.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.updater_id
     *
     * @param updaterId the value for buildings.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.updated_at
     *
     * @return the value of buildings.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.updated_at
     *
     * @param updatedAt the value for buildings.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.version
     *
     * @return the value of buildings.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.version
     *
     * @param version the value for buildings.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}