package com.example.domain;

import java.util.Date;

public class Contracts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.contractor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer contractorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer jointGuarantorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.rent
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer rent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.deposit
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.dues_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer duesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.bank_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.start_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.end_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date endAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contracts.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.id
     *
     * @return the value of contracts.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.id
     *
     * @param id the value for contracts.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.contractor_id
     *
     * @return the value of contracts.contractor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getContractorId() {
        return contractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.contractor_id
     *
     * @param contractorId the value for contracts.contractor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setContractorId(Integer contractorId) {
        this.contractorId = contractorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.joint_guarantor_id
     *
     * @return the value of contracts.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getJointGuarantorId() {
        return jointGuarantorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.joint_guarantor_id
     *
     * @param jointGuarantorId the value for contracts.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setJointGuarantorId(Integer jointGuarantorId) {
        this.jointGuarantorId = jointGuarantorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.shop_id
     *
     * @return the value of contracts.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.shop_id
     *
     * @param shopId the value for contracts.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.building_id
     *
     * @return the value of contracts.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.building_id
     *
     * @param buildingId the value for contracts.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.rent
     *
     * @return the value of contracts.rent
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.rent
     *
     * @param rent the value for contracts.rent
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setRent(Integer rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.deposit
     *
     * @return the value of contracts.deposit
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.deposit
     *
     * @param deposit the value for contracts.deposit
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.dues_id
     *
     * @return the value of contracts.dues_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getDuesId() {
        return duesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.dues_id
     *
     * @param duesId the value for contracts.dues_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setDuesId(Integer duesId) {
        this.duesId = duesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.bank_id
     *
     * @return the value of contracts.bank_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.bank_id
     *
     * @param bankId the value for contracts.bank_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBankId(Integer bankId) {
        this.bankId = bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.start_at
     *
     * @return the value of contracts.start_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.start_at
     *
     * @param startAt the value for contracts.start_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.end_at
     *
     * @return the value of contracts.end_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.end_at
     *
     * @param endAt the value for contracts.end_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.comment
     *
     * @return the value of contracts.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.comment
     *
     * @param comment the value for contracts.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.creator_id
     *
     * @return the value of contracts.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.creator_id
     *
     * @param creatorId the value for contracts.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.created_at
     *
     * @return the value of contracts.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.created_at
     *
     * @param createdAt the value for contracts.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.updater_id
     *
     * @return the value of contracts.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.updater_id
     *
     * @param updaterId the value for contracts.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.updated_at
     *
     * @return the value of contracts.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.updated_at
     *
     * @param updatedAt the value for contracts.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contracts.version
     *
     * @return the value of contracts.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contracts.version
     *
     * @param version the value for contracts.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}