package com.example.domain;

import java.util.Date;

public class Contractors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer jointGuarantorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contractors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.id
     *
     * @return the value of contractors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.id
     *
     * @param id the value for contractors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.name
     *
     * @return the value of contractors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.name
     *
     * @param name the value for contractors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.email
     *
     * @return the value of contractors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.email
     *
     * @param email the value for contractors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.zipcode
     *
     * @return the value of contractors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.zipcode
     *
     * @param zipcode the value for contractors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.address
     *
     * @return the value of contractors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.address
     *
     * @param address the value for contractors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.tel
     *
     * @return the value of contractors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.tel
     *
     * @param tel the value for contractors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.birthday
     *
     * @return the value of contractors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.birthday
     *
     * @param birthday the value for contractors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.shop_id
     *
     * @return the value of contractors.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.shop_id
     *
     * @param shopId the value for contractors.shop_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.joint_guarantor_id
     *
     * @return the value of contractors.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getJointGuarantorId() {
        return jointGuarantorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.joint_guarantor_id
     *
     * @param jointGuarantorId the value for contractors.joint_guarantor_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setJointGuarantorId(Integer jointGuarantorId) {
        this.jointGuarantorId = jointGuarantorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.comment
     *
     * @return the value of contractors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.comment
     *
     * @param comment the value for contractors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.creator_id
     *
     * @return the value of contractors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.creator_id
     *
     * @param creatorId the value for contractors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.created_at
     *
     * @return the value of contractors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.created_at
     *
     * @param createdAt the value for contractors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.updater_id
     *
     * @return the value of contractors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.updater_id
     *
     * @param updaterId the value for contractors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.updated_at
     *
     * @return the value of contractors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.updated_at
     *
     * @param updatedAt the value for contractors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contractors.version
     *
     * @return the value of contractors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contractors.version
     *
     * @param version the value for contractors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}