package com.example.domain;

import java.util.Date;

public class Dues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.price
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dues.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.id
     *
     * @return the value of dues.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.id
     *
     * @param id the value for dues.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.price
     *
     * @return the value of dues.price
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.price
     *
     * @param price the value for dues.price
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.creator_id
     *
     * @return the value of dues.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.creator_id
     *
     * @param creatorId the value for dues.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.created_at
     *
     * @return the value of dues.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.created_at
     *
     * @param createdAt the value for dues.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.updater_id
     *
     * @return the value of dues.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.updater_id
     *
     * @param updaterId the value for dues.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.updated_at
     *
     * @return the value of dues.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.updated_at
     *
     * @param updatedAt the value for dues.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dues.version
     *
     * @return the value of dues.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dues.version
     *
     * @param version the value for dues.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}