package com.example.domain;

import java.util.Date;

public class JointGuarantors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.relation_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column joint_guarantors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.id
     *
     * @return the value of joint_guarantors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.id
     *
     * @param id the value for joint_guarantors.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.name
     *
     * @return the value of joint_guarantors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.name
     *
     * @param name the value for joint_guarantors.name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.email
     *
     * @return the value of joint_guarantors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.email
     *
     * @param email the value for joint_guarantors.email
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.zipcode
     *
     * @return the value of joint_guarantors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.zipcode
     *
     * @param zipcode the value for joint_guarantors.zipcode
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.address
     *
     * @return the value of joint_guarantors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.address
     *
     * @param address the value for joint_guarantors.address
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.tel
     *
     * @return the value of joint_guarantors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.tel
     *
     * @param tel the value for joint_guarantors.tel
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.birthday
     *
     * @return the value of joint_guarantors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.birthday
     *
     * @param birthday the value for joint_guarantors.birthday
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.relation_id
     *
     * @return the value of joint_guarantors.relation_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.relation_id
     *
     * @param relationId the value for joint_guarantors.relation_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.comment
     *
     * @return the value of joint_guarantors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.comment
     *
     * @param comment the value for joint_guarantors.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.creator_id
     *
     * @return the value of joint_guarantors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.creator_id
     *
     * @param creatorId the value for joint_guarantors.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.created_at
     *
     * @return the value of joint_guarantors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.created_at
     *
     * @param createdAt the value for joint_guarantors.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.updater_id
     *
     * @return the value of joint_guarantors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.updater_id
     *
     * @param updaterId the value for joint_guarantors.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.updated_at
     *
     * @return the value of joint_guarantors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.updated_at
     *
     * @param updatedAt the value for joint_guarantors.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column joint_guarantors.version
     *
     * @return the value of joint_guarantors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column joint_guarantors.version
     *
     * @param version the value for joint_guarantors.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}