package com.example.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShopsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public ShopsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOwerIdIsNull() {
            addCriterion("ower_id is null");
            return (Criteria) this;
        }

        public Criteria andOwerIdIsNotNull() {
            addCriterion("ower_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwerIdEqualTo(Integer value) {
            addCriterion("ower_id =", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdNotEqualTo(Integer value) {
            addCriterion("ower_id <>", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdGreaterThan(Integer value) {
            addCriterion("ower_id >", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ower_id >=", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdLessThan(Integer value) {
            addCriterion("ower_id <", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdLessThanOrEqualTo(Integer value) {
            addCriterion("ower_id <=", value, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdIn(List<Integer> values) {
            addCriterion("ower_id in", values, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdNotIn(List<Integer> values) {
            addCriterion("ower_id not in", values, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdBetween(Integer value1, Integer value2) {
            addCriterion("ower_id between", value1, value2, "owerId");
            return (Criteria) this;
        }

        public Criteria andOwerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ower_id not between", value1, value2, "owerId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdIsNull() {
            addCriterion("building_id is null");
            return (Criteria) this;
        }

        public Criteria andBuildingIdIsNotNull() {
            addCriterion("building_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingIdEqualTo(Integer value) {
            addCriterion("building_id =", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdNotEqualTo(Integer value) {
            addCriterion("building_id <>", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdGreaterThan(Integer value) {
            addCriterion("building_id >", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("building_id >=", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdLessThan(Integer value) {
            addCriterion("building_id <", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdLessThanOrEqualTo(Integer value) {
            addCriterion("building_id <=", value, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdIn(List<Integer> values) {
            addCriterion("building_id in", values, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdNotIn(List<Integer> values) {
            addCriterion("building_id not in", values, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdBetween(Integer value1, Integer value2) {
            addCriterion("building_id between", value1, value2, "buildingId");
            return (Criteria) this;
        }

        public Criteria andBuildingIdNotBetween(Integer value1, Integer value2) {
            addCriterion("building_id not between", value1, value2, "buildingId");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andInstaUrlIsNull() {
            addCriterion("insta_url is null");
            return (Criteria) this;
        }

        public Criteria andInstaUrlIsNotNull() {
            addCriterion("insta_url is not null");
            return (Criteria) this;
        }

        public Criteria andInstaUrlEqualTo(String value) {
            addCriterion("insta_url =", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlNotEqualTo(String value) {
            addCriterion("insta_url <>", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlGreaterThan(String value) {
            addCriterion("insta_url >", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlGreaterThanOrEqualTo(String value) {
            addCriterion("insta_url >=", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlLessThan(String value) {
            addCriterion("insta_url <", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlLessThanOrEqualTo(String value) {
            addCriterion("insta_url <=", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlLike(String value) {
            addCriterion("insta_url like", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlNotLike(String value) {
            addCriterion("insta_url not like", value, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlIn(List<String> values) {
            addCriterion("insta_url in", values, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlNotIn(List<String> values) {
            addCriterion("insta_url not in", values, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlBetween(String value1, String value2) {
            addCriterion("insta_url between", value1, value2, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andInstaUrlNotBetween(String value1, String value2) {
            addCriterion("insta_url not between", value1, value2, "instaUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlIsNull() {
            addCriterion("fb_url is null");
            return (Criteria) this;
        }

        public Criteria andFbUrlIsNotNull() {
            addCriterion("fb_url is not null");
            return (Criteria) this;
        }

        public Criteria andFbUrlEqualTo(String value) {
            addCriterion("fb_url =", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlNotEqualTo(String value) {
            addCriterion("fb_url <>", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlGreaterThan(String value) {
            addCriterion("fb_url >", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlGreaterThanOrEqualTo(String value) {
            addCriterion("fb_url >=", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlLessThan(String value) {
            addCriterion("fb_url <", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlLessThanOrEqualTo(String value) {
            addCriterion("fb_url <=", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlLike(String value) {
            addCriterion("fb_url like", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlNotLike(String value) {
            addCriterion("fb_url not like", value, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlIn(List<String> values) {
            addCriterion("fb_url in", values, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlNotIn(List<String> values) {
            addCriterion("fb_url not in", values, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlBetween(String value1, String value2) {
            addCriterion("fb_url between", value1, value2, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andFbUrlNotBetween(String value1, String value2) {
            addCriterion("fb_url not between", value1, value2, "fbUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlIsNull() {
            addCriterion("twt_url is null");
            return (Criteria) this;
        }

        public Criteria andTwtUrlIsNotNull() {
            addCriterion("twt_url is not null");
            return (Criteria) this;
        }

        public Criteria andTwtUrlEqualTo(String value) {
            addCriterion("twt_url =", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlNotEqualTo(String value) {
            addCriterion("twt_url <>", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlGreaterThan(String value) {
            addCriterion("twt_url >", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlGreaterThanOrEqualTo(String value) {
            addCriterion("twt_url >=", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlLessThan(String value) {
            addCriterion("twt_url <", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlLessThanOrEqualTo(String value) {
            addCriterion("twt_url <=", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlLike(String value) {
            addCriterion("twt_url like", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlNotLike(String value) {
            addCriterion("twt_url not like", value, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlIn(List<String> values) {
            addCriterion("twt_url in", values, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlNotIn(List<String> values) {
            addCriterion("twt_url not in", values, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlBetween(String value1, String value2) {
            addCriterion("twt_url between", value1, value2, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andTwtUrlNotBetween(String value1, String value2) {
            addCriterion("twt_url not between", value1, value2, "twtUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlIsNull() {
            addCriterion("hp_url is null");
            return (Criteria) this;
        }

        public Criteria andHpUrlIsNotNull() {
            addCriterion("hp_url is not null");
            return (Criteria) this;
        }

        public Criteria andHpUrlEqualTo(String value) {
            addCriterion("hp_url =", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlNotEqualTo(String value) {
            addCriterion("hp_url <>", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlGreaterThan(String value) {
            addCriterion("hp_url >", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlGreaterThanOrEqualTo(String value) {
            addCriterion("hp_url >=", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlLessThan(String value) {
            addCriterion("hp_url <", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlLessThanOrEqualTo(String value) {
            addCriterion("hp_url <=", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlLike(String value) {
            addCriterion("hp_url like", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlNotLike(String value) {
            addCriterion("hp_url not like", value, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlIn(List<String> values) {
            addCriterion("hp_url in", values, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlNotIn(List<String> values) {
            addCriterion("hp_url not in", values, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlBetween(String value1, String value2) {
            addCriterion("hp_url between", value1, value2, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andHpUrlNotBetween(String value1, String value2) {
            addCriterion("hp_url not between", value1, value2, "hpUrl");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNull() {
            addCriterion("creator_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIsNotNull() {
            addCriterion("creator_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorIdEqualTo(Integer value) {
            addCriterion("creator_id =", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotEqualTo(Integer value) {
            addCriterion("creator_id <>", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThan(Integer value) {
            addCriterion("creator_id >", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("creator_id >=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThan(Integer value) {
            addCriterion("creator_id <", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("creator_id <=", value, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdIn(List<Integer> values) {
            addCriterion("creator_id in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotIn(List<Integer> values) {
            addCriterion("creator_id not in", values, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdBetween(Integer value1, Integer value2) {
            addCriterion("creator_id between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("creator_id not between", value1, value2, "creatorId");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIsNull() {
            addCriterion("updater_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIsNotNull() {
            addCriterion("updater_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdEqualTo(Integer value) {
            addCriterion("updater_id =", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotEqualTo(Integer value) {
            addCriterion("updater_id <>", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdGreaterThan(Integer value) {
            addCriterion("updater_id >", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("updater_id >=", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdLessThan(Integer value) {
            addCriterion("updater_id <", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdLessThanOrEqualTo(Integer value) {
            addCriterion("updater_id <=", value, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdIn(List<Integer> values) {
            addCriterion("updater_id in", values, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotIn(List<Integer> values) {
            addCriterion("updater_id not in", values, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdBetween(Integer value1, Integer value2) {
            addCriterion("updater_id between", value1, value2, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdaterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("updater_id not between", value1, value2, "updaterId");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shops
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 04 12:08:48 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shops
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}