package com.example.domain;

import java.util.Date;

public class Shops {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.ower_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer owerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer buildingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.shop_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String shopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.insta_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String instaUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.fb_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String fbUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.twt_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String twtUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.hp_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String hpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shops.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.id
     *
     * @return the value of shops.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.id
     *
     * @param id the value for shops.id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.ower_id
     *
     * @return the value of shops.ower_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getOwerId() {
        return owerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.ower_id
     *
     * @param owerId the value for shops.ower_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setOwerId(Integer owerId) {
        this.owerId = owerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.building_id
     *
     * @return the value of shops.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.building_id
     *
     * @param buildingId the value for shops.building_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.shop_name
     *
     * @return the value of shops.shop_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.shop_name
     *
     * @param shopName the value for shops.shop_name
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.insta_url
     *
     * @return the value of shops.insta_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getInstaUrl() {
        return instaUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.insta_url
     *
     * @param instaUrl the value for shops.insta_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setInstaUrl(String instaUrl) {
        this.instaUrl = instaUrl == null ? null : instaUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.fb_url
     *
     * @return the value of shops.fb_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getFbUrl() {
        return fbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.fb_url
     *
     * @param fbUrl the value for shops.fb_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setFbUrl(String fbUrl) {
        this.fbUrl = fbUrl == null ? null : fbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.twt_url
     *
     * @return the value of shops.twt_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getTwtUrl() {
        return twtUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.twt_url
     *
     * @param twtUrl the value for shops.twt_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setTwtUrl(String twtUrl) {
        this.twtUrl = twtUrl == null ? null : twtUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.hp_url
     *
     * @return the value of shops.hp_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getHpUrl() {
        return hpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.hp_url
     *
     * @param hpUrl the value for shops.hp_url
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setHpUrl(String hpUrl) {
        this.hpUrl = hpUrl == null ? null : hpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.comment
     *
     * @return the value of shops.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.comment
     *
     * @param comment the value for shops.comment
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.creator_id
     *
     * @return the value of shops.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.creator_id
     *
     * @param creatorId the value for shops.creator_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.created_at
     *
     * @return the value of shops.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.created_at
     *
     * @param createdAt the value for shops.created_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.updater_id
     *
     * @return the value of shops.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.updater_id
     *
     * @param updaterId the value for shops.updater_id
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.updated_at
     *
     * @return the value of shops.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.updated_at
     *
     * @param updatedAt the value for shops.updated_at
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shops.version
     *
     * @return the value of shops.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shops.version
     *
     * @param version the value for shops.version
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}