package com.example.mapper;

import com.example.domain.Banks;
import com.example.domain.BanksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BanksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Banks> selectByExample(BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Banks selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Banks record, @Param("example") BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Banks record, @Param("example") BanksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Banks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banks
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Banks record);
}