package com.example.mapper;

import com.example.domain.Buildings;
import com.example.domain.BuildingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BuildingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Buildings> selectByExample(BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Buildings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Buildings record, @Param("example") BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Buildings record, @Param("example") BuildingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Buildings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Buildings record);
}