package com.example.mapper;

import com.example.domain.Contracts;
import com.example.domain.ContractsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(ContractsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(ContractsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Contracts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Contracts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Contracts> selectByExample(ContractsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Contracts selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Contracts record, @Param("example") ContractsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Contracts record, @Param("example") ContractsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Contracts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contracts
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Contracts record);
}