package com.example.mapper;

import com.example.domain.Contractors;
import com.example.domain.ContractorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(ContractorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(ContractorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Contractors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Contractors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Contractors> selectByExample(ContractorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Contractors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Contractors record, @Param("example") ContractorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Contractors record, @Param("example") ContractorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Contractors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contractors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Contractors record);
}