package com.example.mapper;

import com.example.domain.Dues;
import com.example.domain.DuesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(DuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(DuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Dues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Dues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Dues> selectByExample(DuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Dues selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Dues record, @Param("example") DuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Dues record, @Param("example") DuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Dues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dues
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Dues record);
}