package com.example.mapper;

import com.example.domain.JointGuarantors;
import com.example.domain.JointGuarantorsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JointGuarantorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(JointGuarantorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(JointGuarantorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(JointGuarantors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(JointGuarantors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<JointGuarantors> selectByExample(JointGuarantorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    JointGuarantors selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") JointGuarantors record, @Param("example") JointGuarantorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") JointGuarantors record, @Param("example") JointGuarantorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(JointGuarantors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table joint_guarantors
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(JointGuarantors record);
}