package com.example.mapper;

import com.example.domain.Relations;
import com.example.domain.RelationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int countByExample(RelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByExample(RelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insert(Relations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int insertSelective(Relations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    List<Relations> selectByExample(RelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    Relations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExampleSelective(@Param("record") Relations record, @Param("example") RelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByExample(@Param("record") Relations record, @Param("example") RelationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKeySelective(Relations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relations
     *
     * @mbggenerated Wed Nov 04 12:08:48 JST 2020
     */
    int updateByPrimaryKey(Relations record);
}